export default {
    
      /*
      * 加载状态
      * COMMON
      * Loading开始
      * Loading结束CATALOG_INITDATA_GETDATA_REQUEST
    * */
    LOADING_START: 'LOADING_START',
    LOADING_END: 'LOADING_END',
  
   
    /*
    * 精选分类Tab
    * CATAGORY
    * CATAGORY_NAV_GETDATA_REQUEST: 分类Tab数据请求
    * CATAGORY_NAV_GETDATA_SUCCESS：分类Tab请求成功
    * CATAGORY_NAV_GETDATA_FAILURE：分类Tab请求失败
    * */
    CATAGORY_NAV_GETDATA_REQUEST: 'CATAGORY_NAV_GETDATA_REQUEST',
    CATAGORY_NAV_GETDATA_SUCCESS: 'CATAGORY_NAV_GETDATA_SUCCESS',
    CATAGORY_NAV_GETDATA_FAILURE: 'CATAGORY_NAV_GETDATA_FAILURE',
  
    /*
    * CATALOG
    * 分类页中初始化tab数据和当前分类数据
    * CATALOG_INITDATA_GETDATA_REQUEST: 数据请求
    * CATALOG_INITDATA_GETDATA_SUCCESS: 请求成功
    * CATALOG_INITDATA_GETDATA_FAILURE: 请求失败
    * */
    CATALOG_INITDATA_GETDATA_REQUEST: 'CATALOG_INITDATA_GETDATA_REQUEST',
    CATALOG_INITDATA_GETDATA_FAILURE: 'CATALOG_INITDATA_GETDATA_FAILURE',
  
    /*
    * CATALOG
    * 根据分类ID获取当前商品分类信息跟子分类
    * CATALOG_CATALOGMSG_GETDATA_REQUEST: 数据请求CATALOG_CATALOGMSG_GETDATA_REQUEST
    * CATALOG_CATALOGMSG_GETDATA_SUCCESS: 请求成功
    * CATALOG_CATALOGMSG_GETDATA_FAILURE: 请求失败
    * */
    CATALOG_CATALOGMSG_GETDATA_REQUEST: 'CATALOG_CATALOGMSG_GETDATA_REQUEST',

  
    /*
    * CATALOG
    * 修改分类页面的请求分类ID跟当前TabIndex值CATALOG_CHANGEIDANDTABINDEX
    * */
    CATALOG_CHANGEIDANDTABINDEX: 'CATALOG_CHANGEIDANDTABINDEX',
  
    /*
    * GOODS
    * 在售商品数量
    * GOODS_COUNT_GETDATA_REQUSET: 数据请求
    * GOODS_COUNT_GETDATA_SUCCESS: 请求成功
    * GOODS_COUNT_GETDATA_FAILURE: 请求失败
    * */
    GOODS_COUNT_GETDATA_REQUSET: 'GOODS_COUNT_GETDATA_REQUSET',
    GOODS_COUNT_GETDATA_SUCCESS: 'GOODS_COUNT_GETDATA_SUCCESS',
    GOODS_COUNT_GETDATA_FAILURE: 'GOODS_COUNT_GETDATA_FAILURE',
    /*
    * GOODSSEARCH
    * 商品查询
    * GOODSSEARCH_GETDATA_SUCCESS: 数据请求成功
    * GOODSSEARCH_GETDATA_REQUEST: 请求
    * GOODSSEARCH_GETDATA_FAILURE：失败
    * GOODSSEARCH_CHANGE_PARMAS: 修改请求参数
    * GOODSSEARCH_RESET_STATE: 还原初始化数据
    * GOODSSEARCH_CHANGE_SEARCHVAL_PARMAS: 修改查询的input的值
    * GOODSSEARCH_CHANGE_SORT_PARMAS: 修改排序类别
    * GOODSSEARCH_CHANGE_CATEGORYID_PARMAS: 修改分类
    * */
    GOODSSEARCH_GETDATA_SUCCESS: 'GOODSSEARCH_GETDATA_SUCCESS',
    GOODSSEARCH_GETDATA_REQUEST: 'GOODSSEARCH_GETDATA_REQUEST',
    GOODSSEARCH_GETDATA_FAILURE: 'GOODSSEARCH_GETDATA_FAILURE',
    GOODSSEARCH_CHANGE_PARMAS: 'GOODSSEARCH_CHANGE_PARMAS',
    GOODSSEARCH_RESET_STATE: 'GOODSSEARCH_RESET_STATE',
    GOODSSEARCH_CHANGE_SEARCHVAL_PARMAS: 'GOODSSEARCH_CHANGE_SEARCHVAL_PARMAS',
    GOODSSEARCH_CHANGE_SORT_PARMAS: 'GOODSSEARCH_CHANGE_SORT_PARMAS',
    GOODSSEARCH_CHANGE_CATEGORYID_PARMAS: 'GOODSSEARCH_CHANGE_CATEGORYID_PARMAS',
    /*
    * GOODS
    * 获取商品数据
    * GOODS_LIST_GETDATA_REQUSET: 数据请求
    * GOODS_LIST_GETDATA_SUCCESS: 请求成功
    * GOODS_LIST_GETDATA_FAILURE: 请求失败
    * */
    GOODS_LIST_GETDATA_REQUSET: 'GOODS_LIST_GETDATA_REQUSET',
    GOODS_LIST_GETDATA_SUCCESS: 'GOODS_LIST_GETDATA_SUCCESS',
    GOODS_LIST_GETDATA_FAILURE: 'GOODS_LIST_GETDATA_FAILURE',
  

  
 
  
  }
  